[tool.poetry]
name = "fastapi-do-zero"
version = "0.1.0"
description = ""
authors = ["dunossauro <mendesxeduardo@gmail.com>"]
readme = "README.md"
packages = [{include = "fastapi-do-zero"}]

[tool.poetry.dependencies]
python = "^3.11"
mkdocs = "^1.4.3"
mkdocs-material = "^9.5.1"
taskipy = "^1.11.0"
mkdocs-glightbox = "^0.3.4"
mkdocs-video = "^1.5.0"
mkdocs-git-authors-plugin = "^0.7.2"
mkdocs-git-revision-date-localized-plugin = "^1.2.0"
pillow = "^10.0.0"
cairosvg = "^2.7.0"
mkdocs-with-pdf = "^0.9.3"

[tool.taskipy.tasks]
serve = {cmd="mkdocs serve --dev-addr localhost:8080", help="Executa o servidor local do mkdocs"}
deploy = {cmd="mkdocs gh-deploy", help="Faz o deploy da página em produção"}
slides = {cmd="marp -I slides/brutos/ --html --theme slides/brutos/rose-pine.css --allow-local-files --pdf -o slides/pdf/", help="Gera os slides em pdf"}
slides_html = {cmd="marp -I slides/brutos --html --theme slides/brutos/rose-pine.css --allow-local-files -o slides/html", help="Gera os slides em html (formato usado nas aulas)"}
pdf = {cmd="ENABLE_PDF_EXPORT=1 mkdocs build", help="Cria um pdf único de todo o curso (não otimizado ainda)"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
